export const ticketBarcodePattern = [
  { width: 1, gap: 0 },
  { width: 1, gap: 0 },
  { width: 3, gap: 2 },
  { width: 1, gap: 0 },
  { width: 4, gap: 1 },
  { width: 2, gap: 3 },
  { width: 1, gap: 0 },
  { width: 3, gap: 0 },
  { width: 1, gap: 4 },
  { width: 4, gap: 0 },
  { width: 2, gap: 1 },
  { width: 1, gap: 0 },
  { width: 3, gap: 2 },
  { width: 1, gap: 0 },
  { width: 2, gap: 3 },
  { width: 4, gap: 1 },
  { width: 1, gap: 0 },
  { width: 3, gap: 0 },
  { width: 1, gap: 2 },
  { width: 4, gap: 0 },
] as const;
